### ISSUE TITLE
Make Outline for SEEK Search Display Activity

### ISSUE THREAD

**Issue by Aasiya3** [Aasiya3/ElephantBook_FieldGuide#7]
Nav Bar to return to the splash page and label, display SEEK code entered, and list of containers that will hold individual elephant info.

**Comment by bsakai2000** [comment]
https://stackoverflow.com/questions/39248772/how-to-add-content-in-recyclerview-dynamically

**Comment by bsakai2000** [comment]
https://www.raywenderlich.com/1560485-android-recyclerview-tutorial-with-kotlin
